### ISSUE TITLE
To-Do List SSW 345

### ISSUE THREAD

**Issue by swin0** [swin0/SSW.issue#1]
Issue to keep track of homework tasks

**Comment by swin0** [comment]
# Homework Tasks SSW 345

## To Do 
- [ ] Finish Github issue to do list!

## Completed
- [x] Download Visual Paradigm
- [x] Finish Learn Git Branching modules
